# Generated by Django 4.2.29 on 2026-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('GH', 'Ghana'), ('NG', 'Nigeria')], default='GH', max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.CharField(choices=[('nov5', 'Wednesday, November 5'), ('nov12', 'Wednesday, November 12'), ('nov19', 'Wednesday, November 19'), ('nov25', 'Wednesday, November 25')], max_length=10)),
                ('session_type', models.CharField(choices=[('physical', 'Physical Session'), ('online', 'Online Session')], default='physical', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
