# Generated by Django 4.2.11 on 2026-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('session_type', models.CharField(blank=True, choices=[('physical', 'Physical Session'), ('online', 'Online Session')], max_length=12)),
                ('session_date', models.CharField(choices=[('nov5', 'Wednesday, November 5'), ('nov12', 'Wednesday, November 12'), ('nov19', 'Wednesday, November 19'), ('nov25', 'Wednesday, November 25')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
