# Generated by Django 4.2.29 on 2026-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='session_date',
            field=models.CharField(choices=[('2026-06-03', 'Wednesday, June 3, 2026'), ('2026-06-10', 'Wednesday, June 10, 2026'), ('2026-06-17', 'Wednesday, June 17, 2026'), ('2026-06-24', 'Wednesday, June 24, 2026')], max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='session_date',
            field=models.CharField(choices=[('2026-06-03', 'Wednesday, June 3, 2026'), ('2026-06-10', 'Wednesday, June 10, 2026'), ('2026-06-17', 'Wednesday, June 17, 2026'), ('2026-06-24', 'Wednesday, June 24, 2026')], max_length=10),
        ),
    ]
