# Generated by Django 4.2.29 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_reservation_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='session_date',
            field=models.CharField(choices=[('2026-07-01', 'Wednesday, July 1, 2026'), ('2026-07-04', 'Saturday, July 4, 2026'), ('2026-07-08', 'Wednesday, July 8, 2026'), ('2026-07-11', 'Saturday, July 11, 2026'), ('2026-07-15', 'Wednesday, July 15, 2026'), ('2026-07-18', 'Saturday, July 18, 2026'), ('2026-07-22', 'Wednesday, July 22, 2026'), ('2026-07-25', 'Saturday, July 25, 2026'), ('2026-07-29', 'Wednesday, July 29, 2026')], max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='session_date',
            field=models.CharField(choices=[('2026-07-01', 'Wednesday, July 1, 2026'), ('2026-07-04', 'Saturday, July 4, 2026'), ('2026-07-08', 'Wednesday, July 8, 2026'), ('2026-07-11', 'Saturday, July 11, 2026'), ('2026-07-15', 'Wednesday, July 15, 2026'), ('2026-07-18', 'Saturday, July 18, 2026'), ('2026-07-22', 'Wednesday, July 22, 2026'), ('2026-07-25', 'Saturday, July 25, 2026'), ('2026-07-29', 'Wednesday, July 29, 2026')], max_length=10),
        ),
    ]
