# Generated by Django 4.2.29 on 2026-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_reservation_session_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog article',
                'verbose_name_plural': 'Blog articles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('physical', 'Physical Session'), ('online', 'Online Session')], max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Class date',
                'verbose_name_plural': 'Class dates',
                'ordering': ('display_order', 'date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.TextField(default='Think Clearly.\nFeel Balance.\nWork Better.')),
                ('hero_subtitle', models.TextField(blank=True, default='A simple, effortless technique to reduce stress, sharpen focus, and support better living.')),
                ('cta_button_text', models.CharField(default='Watch Video', max_length=80)),
                ('cta_button_link', models.CharField(blank=True, max_length=255)),
                ('hero_youtube_url', models.URLField(default='https://www.youtube.com/embed/AL_c-sV9zXc?enablejsapi=1')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage content',
                'verbose_name_plural': 'Homepage content',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='session_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='session_date',
            field=models.CharField(max_length=10),
        ),
    ]
