# Generated by Django 4.2.29 on 2026-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_blogarticle_classdate_homepagecontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdate',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online Session')], default='online', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online Session')], default='online', max_length=12),
        ),
        migrations.AlterField(
            model_name='submission',
            name='session_type',
            field=models.CharField(blank=True, choices=[('online', 'Online Session')], default='online', max_length=12),
        ),
    ]
