# Generated by Django 4.2.29 on 2026-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_classdate_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdate',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='The online meeting URL included in the reservation confirmation email.'),
        ),
    ]
