# Generated by Django 4.2.29 on 2026-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_classdate_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
