# Generated by Django 4.2.29 on 2026-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_submission_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
