# Generated by Django 4.2.29 on 2026-09-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_submission_reminder_1h_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('registration_complete', 'Registration completion'), ('meeting_reminder_24h', '24-hour meeting reminder'), ('meeting_reminder_1h', '1-hour meeting reminder')], max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Django template syntax is supported, for example {{ user_first_name }}.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ('slug',),
            },
        ),
    ]
