# Generated by Django 4.2.29 on 2026-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_seed_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('meeting_link', models.URLField(blank=True, help_text='This link is included in every registration and reminder email.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting settings',
                'verbose_name_plural': 'Meeting settings',
            },
        ),
    ]
