# Generated by Django 4.2.29 on 2026-10-01 18:03

from django.db import migrations, models
import django.utils.timezone


def preserve_existing_publication_dates(apps, schema_editor):
    BlogArticle = apps.get_model('landing', 'BlogArticle')
    BlogArticle.objects.filter(publication_date__isnull=True).update(
        publication_date=models.F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_remove_classdate_meeting_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ('-publication_date', '-created_at'), 'verbose_name': 'Blog article', 'verbose_name_plural': 'Blog articles'},
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='blog_cards/'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='carousel_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='include_in_carousel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(preserve_existing_publication_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogarticle',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
