"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config as env_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*l%zm_&i64ee9a*$s_tqz22#sv(#vquc1=dd&_ijlk-zwa97*p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['OjemeOjikutu.pythonanywhere.com',
                 '127.0.0.1', 'tmnigeria.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

USE_POSTGRES = env_config("USE_POSTGRES", default=os.getenv("USE_POSTGRES", "False"), cast=bool)
DB_NAME = env_config("DB_NAME", default=os.getenv("DB_NAME", ""))
if USE_POSTGRES and DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': env_config("DB_USER", default=os.getenv("DB_USER", "")),
            'PASSWORD': env_config("DB_PASSWORD", default=os.getenv("DB_PASSWORD", "")),
            'HOST': env_config("DB_HOST", default=os.getenv("DB_HOST", "localhost")),
            'PORT': env_config("DB_PORT", default=os.getenv("DB_PORT", "5432")),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'landing' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration (env-driven)
EMAIL_BACKEND = env_config(
    "EMAIL_BACKEND",
    default=env_config("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"),
)
EMAIL_HOST = env_config("EMAIL_HOST", default=env_config("DJANGO_EMAIL_HOST", default="smtp.gmail.com"))
EMAIL_PORT = env_config("EMAIL_PORT", default=env_config("DJANGO_EMAIL_PORT", default="587"), cast=int)
EMAIL_HOST_USER = env_config("EMAIL_HOST_USER", default=env_config("DJANGO_EMAIL_HOST_USER", default=""))
EMAIL_HOST_PASSWORD = env_config("EMAIL_HOST_PASSWORD", default=env_config("DJANGO_EMAIL_HOST_PASSWORD", default=""))
EMAIL_USE_TLS = env_config("EMAIL_USE_TLS", default=env_config("DJANGO_EMAIL_USE_TLS", default="True"), cast=bool)
EMAIL_USE_SSL = env_config("EMAIL_USE_SSL", default=env_config("DJANGO_EMAIL_USE_SSL", default="False"), cast=bool)
DEFAULT_FROM_EMAIL = env_config(
    "DEFAULT_FROM_EMAIL",
    default=env_config("DJANGO_DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER or "no-reply@example.com"),
)
SERVER_EMAIL = env_config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
LANDING_ADMIN_EMAIL = env_config("LANDING_ADMIN_EMAIL", default=DEFAULT_FROM_EMAIL)
